[package]
name = "extest"
version = "1.0.3"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
evdev = "0.12.1"
once_cell = "1.17.1"
wayland-client = "0.30.1"
wayland-protocols = { version = "0.30.0", features = ["client", "unstable"] }
